### ISSUE TITLE
[MacOS] No current release able to unpack 1.5.4 assets

### ISSUE THREAD

**Issue by timelessthee** [Pathoschild/StardewXnbHack#13]
Similar to Issue #9, On MacOS StardewXnbHack 1.0.4 fails to unpack some assets for Stardew Valley 1.5.4

It is stated that this is fixed in StardewXnbHack 1.0.5, however that release is only compatibile with Stardew Valley 1.5.5.

So is there any way to unpack assets for Stardew Valley 1.5.4 currently on MacOS? 
As there doesn't seem to be any release that supports this.

**Comment by Pathoschild** [comment]
Unfortunately it's not really feasible to fix it in Stardew Valley 1.5.4. The fix is in the newer version of MonoGame, which is bundled into the game files. A temporary workaround is to [install the Stardew Valley 1.5.5 beta](https://www.patreon.com/posts/55035968) though, which is available on macOS too.

**Comment by Pathoschild** [comment]
Stardew Valley 1.5.5 is now released to all players.
